שבת שלום!

diff --git a/Server/Api/Dockerfile b/Server/Api/Dockerfile
--- a/Server/Api/Dockerfile
+++ b/Server/Api/Dockerfile
@@ -60,6 +60,11 @@ RUN dotnet publish "Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAp
 FROM base AS final
 WORKDIR /app
 ENV LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu
+RUN ldconfig
+RUN find / -name "libleptonica*.so*" || echo "libleptonica not found"
+RUN ln -s /usr/local/lib/libleptonica*.so /usr/local/lib/libleptonica-1.82.0.so || echo "symlink already exists or not needed"
 
 COPY --from=publish /app/publish .
 ENTRYPOINT ["dotnet", "Api.dll"]
+
+
